### ISSUE TITLE
Specify the stroke-width of the path

### ISSUE THREAD

**Issue by cchauche** [mveytsman/heroicons_elixir#9]
Would it be possible to add an option to change the `stroke-width` attribute of the `path` element in the SVG?

For my current case I'd like to use a Heroicon but with stroke-width set to 1:

```html
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>
```

The tag could have an optional attribute so it would be called like:
```elixir
<Heroicons.Outline.user_circle class="h6 w-6" stroke-width="1" />
```

**Comment by greven** [comment]
Hey, @mveytsman correct me if I'm wrong, but with the recent build this issue is already solved, so it can be closed?
Right now you can pass the stroke-width as assign to the Functional Component and it will affect the SVG.

**Comment by mveytsman** [comment]
That's absolutely correct thanks @greven!

**Comment by mveytsman** [comment]
This is currently broken, re-opening

**Comment by greven** [comment]
@mveytsman  So this is the same reason that if I add width and height the compiler keeps warning me about unknown attribute:

![image](https://user-images.githubusercontent.com/213226/192308856-5c0aecb0-46ca-459d-b378-0495559a2e89.png)

I thought the :global attr would allow valid HTML attributes but it still warns on width and height. 🤔 
width, height and stroke-width should be common options when using icons.
Width and Height are important for SVG since before CSS applies it prevents the icons from being rendered in huge sizes so it reduces page elements moving around.

**Comment by mveytsman** [comment]
@greven `width` and `height` were *just* added to the globals in live view (but this obviously hasn't shipped yet 
https://github.com/phoenixframework/phoenix_live_view/commit/feeb5f86d8c4429909816e6f467a49a976cb4084

I think there's still an issue with stroke-width but I havent' tested it enough...

**Comment by greven** [comment]
> @greven `width` and `height` were *just* added to the globals in live view (but this obviously hasn't shipped yet 
> https://github.com/phoenixframework/phoenix_live_view/commit/feeb5f86d8c4429909816e6f467a49a976cb4084
> 
> I think there's still an issue with stroke-width but I havent' tested it enough...

Oh that's great, missed that, thanks. The amount of warnings I had because of that was a bit unsettling!

**Comment by mveytsman** [comment]
Closed in https://github.com/mveytsman/heroicons_elixir/commit/c712f72aa8815c899119092472bf237b9b5f77c3
